// End-to-end test of the app against the real database rules (see run.sh).
const {chromium}=require('playwright'); let errs=[]; const {execSync}=require('child_process'); const fs=require('fs'); const zlib=require('zlib'); const os=require('os'); const path=require('path');
const APP=process.env.APP_URL||'http://localhost:4173', DB=process.env.PMDB||'pme2e', SHOTS=process.env.SHOTS||'';
const psql=(q)=>execSync(`psql -d ${DB} -tAc "${q.replace(/"/g,'\\"')}"`).toString().trim();
// Fixtures: small PNG photos and a one-page PDF, generated so the repo carries no binary test files.
function png(w,h,rgb){ const raw=Buffer.alloc((w*3+1)*h); for(let y=0;y<h;y++){ raw[y*(w*3+1)]=0; for(let x=0;x<w;x++){ const o=y*(w*3+1)+1+x*3; raw[o]=(rgb[0]+x)&255; raw[o+1]=(rgb[1]+y)&255; raw[o+2]=rgb[2]; } }
  const chunk=(t,d)=>{ const l=Buffer.alloc(4); l.writeUInt32BE(d.length); const td=Buffer.concat([Buffer.from(t),d]); const c=Buffer.alloc(4); c.writeUInt32BE(zlib.crc32(td)>>>0); return Buffer.concat([l,td,c]); };
  const ih=Buffer.alloc(13); ih.writeUInt32BE(w,0); ih.writeUInt32BE(h,4); ih[8]=8; ih[9]=2; return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',ih),chunk('IDAT',zlib.deflateSync(raw)),chunk('IEND',Buffer.alloc(0))]); }
function pdf(){ const objs=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 200] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',null,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];
  const txt='BT /F1 18 Tf 40 100 Td (Menu offer) Tj ET'; objs[3]='<< /Length '+txt.length+' >>\nstream\n'+txt+'\nendstream';
  let out='%PDF-1.4\n', offs=[]; objs.forEach((o,i)=>{ offs.push(out.length); out+=(i+1)+' 0 obj\n'+o+'\nendobj\n'; });
  const x=out.length; out+='xref\n0 6\n0000000000 65535 f \n'+offs.map(o=>String(o).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+x+'\n%%EOF\n'; return Buffer.from(out,'latin1'); }
const FX=fs.mkdtempSync(path.join(os.tmpdir(),'pm-fx-')); const fx=(n,b)=>{ const p=path.join(FX,n); fs.writeFileSync(p,b); return p; };
const COVER=fx('cover.png',png(320,240,[200,120,90])), V1=fx('visit1.png',png(400,300,[90,140,80])), V2=fx('visit2.png',png(300,400,[60,90,160])), MENU=fx('menu.pdf',pdf());
const shot=(p,n,o)=>SHOTS? p.screenshot({path:path.join(SHOTS,n),...(o||{})}) : Promise.resolve();
const log=(...a)=>console.log(...a);
let fails=0; const check=(cond,msg)=>{ if(cond) log('  ok  '+msg); else { fails++; log('  FAIL '+msg); } };
(async()=>{ const b=await chromium.launch();
 const mk=async(name)=>{ const c=await b.newContext({viewport:{width:390,height:844},acceptDownloads:true}); const p=await c.newPage();
   p.on('pageerror',e=>errs.push(name+': '+e.message)); p.on('console',m=>{ if((m.type()==='error'||m.type()==='warning')&&!/WebSocket/.test(m.text())) errs.push(name+' console: '+m.text().slice(0,300)); });
   p.on('response',r=>{ if(r.status()>=400 && !/realtime/.test(r.url())) errs.push(name+' HTTP '+r.status()+' '+r.request().method()+' '+r.url().replace('http://localhost:54321','')); });
   await p.goto(APP); return {p,c}; };
 const signup=async(p,email)=>{ await p.waitForSelector('.auth-card'); await p.click('[data-auth=to-signup]'); await p.fill('#a-email',email); await p.fill('#a-pw','Blue-Lagoon-2028'); await p.fill('#a-pw2','Blue-Lagoon-2028'); await p.click('[data-auth=signup]'); await p.waitForSelector('#a-code'); await p.fill('#a-code','123456'); await p.click('[data-auth=confirm]'); };
 const tab=async(p,v)=>{ await p.click(v==='settings'?'.gear':`.tabs [data-act=tab][data-v=${v}]`); await p.waitForTimeout(150); };
 const settle=async(p)=>{ for(let i=0;i<40;i++){ const s=await p.textContent('#status').catch(()=>''); if(/All saved/.test(s)) return; await p.waitForTimeout(250);} };

 log('— A: sign-up, onboarding'); const {p:A,c:CA}=await mk('A'); await signup(A,'alice@test.io');
 await A.waitForSelector('#o-p1'); await A.fill('#o-p1','Emma'); await A.fill('#o-p2','Alex'); await A.fill('#o-date','2028-05-20'); await A.fill('#o-cap','80'); await A.selectOption('#o-cur','CHF'); await A.click('[data-ob=go]');
 await A.waitForSelector('.hm-hero'); check(/E&A/.test(await A.textContent('header h1')),'header shows initials E&A');
 check(psql("select partner1_name||'/'||partner2_name||'/'||guest_capacity||'/'||currency from weddings")==='Emma/Alex/80/CHF','wedding stored with names, capacity, currency');

 log('— Venues'); await tab(A,'loc'); await A.click('[data-act=addloc]'); await A.waitForSelector('#f-name');
 await A.fill('#f-name','Villa Rosa'); await A.fill('#f-region','Tuscany'); await A.fill('#f-price',"28'000 for 80 guests");
 await A.click('.q#q-k1 .tick.ok'); await A.click('.q#q-k2 .tick.issue'); await A.fill('#n-k2','No indoor space');
 await A.locator('.cal-grid .day').nth(20).click(); await A.locator('.cal-grid .day').nth(25).click(); await A.locator('.cal-grid .day').nth(25).click();
 await A.locator('#t-out').fill('8'); await A.locator('#t-out').dispatchEvent('change');
 await A.click('.vend summary'); await A.check('#vd-0');
 await A.click('.rkbtn.r1'); await A.click('.star >> nth=3');
 await A.setInputFiles('#photo-in',COVER); await A.waitForSelector('img.photo',{timeout:10000});
 await A.setInputFiles('#vph-in',[V1,V2]); await A.waitForSelector('.gal img',{timeout:15000}); await A.waitForTimeout(500); await shot(A,'pm3-gallery.png'); await A.click('[data-act=galclose]');
 await shot(A,'pm3-check.png',{fullPage:false});
 await settle(A);
 const loc=JSON.parse(psql("select data from entities where kind='loc'"));
 check(loc.name==='Villa Rosa' && loc.answers.k1.s==='ok' && loc.answers.k2.n==='No indoor space','venue fields and answers stored');
 check(loc.answers.v1.dates.length===1 && loc.answers.v1.contested.length===1,'calendar dates (green + yellow) stored');
 check(loc.answers.z1.times.out===8 && loc.answers.d2.vendors.length===1 && loc.rank===1 && loc.rating===4,'curfew, vendors, rank, rating stored');
 check(/^ph\//.test(loc.photo) && loc.visitPhotos.length===2,'cover photo and 2 visit photos stored as files');
 check(+psql("select count(*) from storage.objects")===3,'3 files in private storage');
 log('— Planning'); await A.click('.subnav [data-v=plan]'); await A.waitForSelector('.svc');
 await A.fill('[data-plan=ps1][data-pk=p]','9500'); await A.fill('[data-plan=ps1][data-pk=vat]','8.1'); await A.fill('[data-plan=ps2][data-pk=p]',"12'000"); await A.click('[data-act=svctodo][data-s=ps3]');
 await A.fill('#pdisc','5'); await A.waitForTimeout(200);
 const tot=(await A.textContent('.ps-calc .tot')).replace(/\s+/g,' '); log('    total:',tot);
 check(/21.?156\.03/.test(tot),'total: 9,500 + 8.1 % VAT + 12,000 − 5 % = 21,156.03');
 await A.selectOption('[data-pgrp=ps8]','__new'); await A.waitForSelector('.pgrp'); await A.fill('.pgrp [data-pgk=p]','4000');
 await A.setInputFiles('#pf-ps2',MENU); await A.waitForSelector('.fchip button[data-act=fopen]',{timeout:10000});
 await A.click('.fchip button[data-act=fopen]'); await A.waitForTimeout(4000); const pv=await A.innerHTML('#pdfv'); check(/canvas/.test(pv),'PDF offer opens in viewer '+(/canvas/.test(pv)?'':pv.slice(0,200))); await shot(A,'pm3-pdf.png'); await A.click('[data-act=docclose]');
 await shot(A,'pm3-plan.png',{fullPage:false});
 await A.click('.loc-chip.add'); await A.fill('#f-name','Castello Blu'); await A.click('.loc-chip.add'); await A.waitForSelector('.modal'); check(/2 venues/.test(await A.textContent('.modal')),'third venue blocked in free version (client)'); await A.click('.modal [data-act=modalno]');
 await A.click('.subnav [data-v=cmp]'); await A.waitForSelector('table'); await shot(A,'pm3-cmp.png',{fullPage:true}); check((await A.locator('thead th').count())===3,'comparison shows 2 venues');
 await A.click('.subnav [data-v=check]'); await A.click('.loc-chip:has-text("Castello")'); await A.click('[data-act=locarchask]'); await A.fill('#arch-reason','too far'); await A.click('[data-act=modalok]');
 await A.click('.subnav [data-v=arch]'); check(/too far/.test(await A.textContent('.arch')),'archived venue with reason in archive');

 log('— Guests'); await tab(A,'guests'); await A.click('[data-act=gadd]'); const gid=await A.getAttribute('.grow.open','id');
 const G='#'+gid.slice(3); await A.fill(`#g-${gid.slice(3)}-fn`,'Sam'); await A.fill(`#g-${gid.slice(3)}-ln`,'Smith');
 await A.check(`.grow.open [data-gchk=plusOn]`); await A.fill(`#g-${gid.slice(3)}-plus\\.fn`,'Kim'); await A.selectOption(`#g-${gid.slice(3)}-kids`,'2'); await A.selectOption(`#g-${gid.slice(3)}-rsvp`,'yes'); await A.selectOption(`#g-${gid.slice(3)}-side`,'p2');
 await A.check('.grow.open [data-gchk=stdSent]'); await A.click('.grow.open [data-act=gstd][data-v=physical]'); await A.check('.grow.open [data-gday=main]');
 await A.click('.grow.open [data-act=gstdr][data-v=yes]'); await A.fill(`#g-${gid.slice(3)}-allergies`,'nuts'); await shot(A,'pm3-guest.png');
 await A.click('.grow.open .btn.sage'); await settle(A);
 const g=JSON.parse(psql(`select data from entities where kind='guest' and id='${gid.slice(3)}'`));
 check(g.stdResp==='yes','save-the-date answer stored'); check(g.fn==='Sam' && g.plusOn && g.plus.fn==='Kim' && g.kids===2 && g.side==='p2' && g.stdSent && g.stdType==='physical' && g.days[0]==='main','guest with companion, children, side, save-the-date, days stored');
 await A.click('[data-act=gimp]'); await A.fill('#gimp-text','First name\tLast name\tChildren\tCompanion\tSave the date\tInvitation sent\n'+Array.from({length:20},(_,i)=>`G${i}\tTest\t0\t${i%2?'yes':''}\t${i%3?'digital':''}\t${i%2?'yes':''}`).join('\n'));
 await A.click('[data-act=gimpok]'); await A.waitForTimeout(300); log('    toast:', await A.textContent('#toast').catch(()=>'-'));
 await settle(A); const heads=+psql("select sum(guest_heads(data)) from entities where kind='guest' and not deleted"); check(heads<=30,'import respects 30-person limit (server has '+heads+')');
 await A.click('[data-act=gfhide]'); await A.selectOption('#gf-stdr','yes'); check((await A.locator('.grow').count())===1,'filter save-the-date answer positive'); await A.selectOption('#gf-stdr',''); await A.selectOption('#gf-std','physical'); check((await A.locator('.grow').count())===1,'filter save-the-date printed'); await A.click('[data-act=gfclear]');
 const [dl]=await Promise.all([A.waitForEvent('download'),A.click('[data-act=gexport]')]); const csv=fs.readFileSync(await dl.path(),'utf8'); check(/Sam/.test(csv) && /Kim/.test(csv),'CSV export contains guests');
 await shot(A,'pm3-guests.png');
 log('— Seating, schedule, tasks'); await tab(A,'seat'); await A.click('[data-act=tbquick]'); await A.click('.pc[data-act=seatpick]:has-text("Sam")'); await A.click('.tb >> nth=0'); await A.waitForTimeout(200);
 check(/4\/10/.test(await A.textContent('.tb >> nth=0')),'household seated at table (4/10)'); await shot(A,'pm3-seat.png');
 await tab(A,'tasks'); await A.click('.vhead [data-act=tnew]'); await A.fill('#t-title','Book photographer'); await A.fill('#t-newitem','Ask 3 quotes'); await A.press('#t-newitem','Enter'); await A.click('.modal [data-act=tclose]');
 await A.click('.tk [data-act=tmove]'); check((await A.locator('.kb-col[data-col=doing] .tk').count())===1,'task moved to Ongoing');
 await tab(A,'agenda'); await A.click('.vhead [data-act=agnew]'); await A.fill('#ag-title','Ceremony'); await A.fill('#ag-start','15:00'); await A.dispatchEvent('#ag-start','change'); await A.fill('#ag-end','15:45'); await A.dispatchEvent('#ag-end','change');
 await A.selectOption('#ag-lsel',{index:1}); await A.click('[data-act=aglinkadd]'); await A.click('.modal [data-act=agclose]'); await A.waitForSelector('.ag-card');
 check(/Ceremony/.test(await A.textContent('.ag')) && /Book photographer/.test(await A.textContent('.ag')),'schedule item with linked task'); await shot(A,'pm3-agenda.png');
 await tab(A,'home'); await A.waitForSelector('.hm-hero'); await shot(A,'pm3-home.png',{fullPage:true}); log('    kpis:',(await A.textContent('.hm-hero')).replace(/\s+/g,' '));
 await settle(A);

 log('— Undo / redo'); await tab(A,'tasks'); const nT=()=>+psql("select count(*) from entities where kind='task' and not deleted");
 const before=nT(); await A.click('.vhead [data-act=tnew]'); await A.fill('#t-title','Undo me'); await A.click('.modal [data-act=tclose]'); await A.waitForTimeout(900); await settle(A);
 check(nT()===before+1,'task created'); await A.click('#hundo'); await A.waitForTimeout(300); await settle(A); check(nT()===before && !/Undo me/.test(await A.textContent('.kb')),'undo removes the task (app and server)');
 await A.click('#hredo'); await A.waitForTimeout(300); await settle(A); check(nT()===before+1 && /Undo me/.test(await A.textContent('.kb')),'redo brings it back');
 await tab(A,'loc'); await A.click('.subnav [data-v=check]'); await A.click('[data-act=galopen]'); await A.click('[data-act=galdelask]'); await A.click('[data-act=galdel]'); await A.click('[data-act=galclose]').catch(()=>{}); await A.waitForTimeout(900); await settle(A);
 check(+psql("select count(*) from storage.objects where name like '%/vp/%'")===2,'deleted photo kept in storage while undo is possible');
 await A.click('#hundo'); await A.waitForTimeout(300); await settle(A); check(JSON.parse(psql("select data from entities where kind='loc' and data->>'name'='Villa Rosa'")).visitPhotos.length===2,'undo restores the deleted photo');
 await A.setViewportSize({width:390,height:844}); await tab(A,'home'); const nav=await A.evaluate(()=>{ const r=document.querySelector('nav.tabs').getBoundingClientRect(); return {bottom:Math.round(r.bottom),h:Math.round(r.height),icons:document.querySelectorAll('nav.tabs .tab .ti').length}; });
 check(nav.bottom===844 && nav.icons===6,'mobile: tab bar with icons at the bottom'); await shot(A,'pm4-mobile.png');
log('— Partner B joins'); await A.click('[data-act=tab][data-v=settings]'); await A.click('[data-act=invnew]'); await A.waitForSelector('.codebox code'); const code=await A.textContent('.codebox code');
 await shot(A,'pm3-settings.png',{fullPage:true});
 check(+psql(`select count(*) from wedding_invites where code_hash='${code.replace('-','')}'`)===0,'invite code stored hashed');
 const {p:B,c:CB}=await mk('B'); await signup(B,'bob@test.io'); await B.waitForSelector('[data-ob=m-join]'); await B.click('[data-ob=m-join]'); await B.fill('#o-code','AAAAA-BBBBB'); await B.click('[data-ob=go]'); await B.waitForSelector('.vis-msg.err'); check(/not valid/.test(await B.textContent('.vis-msg.err')),'wrong invite code rejected');
 await B.fill('#o-code',code.toLowerCase()); await B.click('[data-ob=go]'); await B.waitForSelector('.hm-hero'); await tab(B,'guests'); check(/Sam Smith/.test(await B.textContent('.glist')),'partner sees guests');
 log('— Concurrent edits are merged'); await tab(A,'guests');
 await B.click(`#gr-${gid.slice(3)} .ghead`); await B.fill(`#g-${gid.slice(3)}-mobile`,'+41 79 000 00 00');
 await A.click(`#gr-${gid.slice(3)} .ghead`); await A.fill(`#g-${gid.slice(3)}-note`,'Vegetarian aunt');
 await A.waitForTimeout(2500); await B.waitForTimeout(500); await A.evaluate(()=>document.dispatchEvent(new Event('visibilitychange'))); await B.evaluate(()=>document.dispatchEvent(new Event('visibilitychange'))); await A.waitForTimeout(2500);
 const gm=JSON.parse(psql(`select data from entities where kind='guest' and id='${gid.slice(3)}'`)); check(gm.mobile==='+41 79 000 00 00' && gm.note==='Vegetarian aunt','both edits of the same guest survive (merge)');
 log('— Stranger'); const {p:C}=await mk('C'); await signup(C,'eve@test.io'); await C.waitForSelector('#o-p1'); const leak=await C.evaluate(async()=>{ const r=await fetch('http://localhost:54321/rest/v1/entities?select=*',{headers:{apikey:'x',authorization:'Bearer '+(Object.values(localStorage).join(' ').match(/eyJ[\w-]+\.[\w-]+\.[\w-]+/)||[''])[0]}}); const j=await r.json(); return Array.isArray(j)? j.length : j; }); check(leak===0,'stranger reads 0 items via API ('+JSON.stringify(leak)+')');
 log('— Offline'); await CA.setOffline(true); await tab(A,'tasks'); await A.click('.vhead [data-act=tnew]'); await A.fill('#t-title','Offline task'); await A.click('.modal [data-act=tclose]'); await A.waitForTimeout(1500);
 const st=await A.textContent('#status'); check(/Offline/.test(st),'offline status shown: '+st.trim());
 await CA.setOffline(false); await A.evaluate(()=>window.dispatchEvent(new Event('online'))); await settle(A); check(+psql("select count(*) from entities where kind='task' and data->>'t'='Offline task'")===1,'offline edit sent after reconnect');
 log('— Reload keeps data'); await A.reload(); await A.waitForSelector('.hm-hero, .kb, .tabs'); await tab(A,'guests'); check((await A.locator('.grow').count())>=2,'data after reload');
 log('— Delete account (partner)'); await tab(B,'settings'); await B.click('[data-act=accdelask]'); await B.fill('#acc-confirm','DELETE'); await B.click('[data-act=accdel]'); await B.waitForSelector('#again',{timeout:10000});
 check(+psql("select count(*) from weddings")===1 && +psql("select count(*) from wedding_members")===1 && +psql("select count(*) from auth.users where email='bob@test.io'")===0,'partner account deleted, shared wedding stays with A');
 log('errors:', errs.filter(e=>!/FREE_LIMIT|offline|ERR_INTERNET_DISCONNECTED|Failed to fetch/.test(e)));
 log(fails? fails+' FAILED' : 'ALL E2E CHECKS PASSED');
 await b.close(); process.exit(fails?1:0);
 })().catch(e=>{ console.error(e); console.log('errors so far:', errs); process.exit(1); });
